apiVersion: v1
data:
  config-local.js: |
    define([], function () {
      var configLocal = {};

      var getUrl = window.location;



      configLocal.api = {
        name: 'ohdsi',
        url: 'https://immune-crayfish-expert.ngrok-free.app/WebAPI/' 
      };

      return configLocal;
    });

kind: ConfigMap
metadata:
  name: atlas-configmap
  namespace: ohdsi