apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: broadsea-db
  name: broadsea-db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: broadsea-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-10-13T23:07:26+11:00"
      creationTimestamp: null
      labels:
        app: broadsea-db
    spec:
      containers:
      - image: ohdsi/broadsea-atlasdb:2.2.0
        imagePullPolicy: IfNotPresent
        name: broadsea-atlasdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
 