apiVersion: v1
data:
  config-local.js: |
    define([], function () {
      var configLocal = {};

      var getUrl = window.location;



      configLocal.api = {
        name: 'ohdsi',
        url: 'http://203.101.238.248.nip.io/WebAPI/' 
      };

      return configLocal;
    });

kind: ConfigMap
metadata:
  name: atlas-configmap