apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapi
  name: webapi
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapi
  type: NodePort
status:
  loadBalancer: {}
