# using the following command to generate Atlas secrets for various databases. 
#  kubectl create secret generic my-secret --from-literal=key1=supersecret --from-literal=key2=topsecret --dry-run -oyaml
# Question is what passwords and user names are needed. 
# Atlas --no passwords
# Postgres
          #- name: POSTGRES_PASSWORD (optional)
          #  value: admin1
          #    ALTER ROLE ohdsi_admin_user WITH PASSWORD 'admin1'; ** and it sits in init script file. 
          #    ALTER ROLE ohdsi_app_user WITH PASSWORD 'app1'; ** and it sits in init script file. 
# Webapi
      #         - name: DATASOURCE_USERNAME 
       #   value: ohdsi_admin_user  ** this is repeat and required. Env variables. 
       # - name: DATASOURCE_PASSWORD
       #   value: admin1
       #        - name: FLYWAY_DATASOURCE_PASSWORD ** this is repeat and required. Env variables. 
       #   value: admin1

# usernames and passwords needed. I will mark it with **. Also mention requirements. 
# there is a script add CDM database and it has its own passwords. 
# kubectl create secret generic atlas-secrets --from-literal=POSTGRES_PASSWORD=admin1 --from-literal=ohdsi_admin_user=admin1 --from-literal=FLYWAY_DATASOURCE_PASSWORD=admin1 --from-literal=ohdsi_app_user=app1 --dry-run -oyaml
# What next 

#-------------------
# Using secrets set as env variables to set passwords.
#You can store the result of a shell command inside a psql variable like this:

#\set afile `echo "$outputdir/a.csv"`
#COPY (SELECT * FROM a) TO :'afile';
#------------------------

apiVersion: v1
data:
  flyway-datasource-password: YWRtaW4x
  postgres-password: YWRtaW4x
  ohdsi-admin-user: YWRtaW4x
  ohdsi-app-user: YXBwMQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: atlas-secrets
  namespace: ohdsi